-- DAY 16 Q1

/* IMP 
Problem Description:
The finance team wants to audit high-value customers who spent more on a single order than the total combined revenue generated by any item in the 'Beverages' category. 
Write an SQL query to pull the customer ID, full name, and email.
Use a subquery to find individual order amounts that surpass the maximum value computed from a nested correlated sum calculation of delivered beverage items,
and 
ensure the customer has never had a cancelled order by integrating an EXCEPT set operator clause.

case=1
output=
customer_id	full_name	email
1	Amit Sharma	amit.sharma@gmail.com
2	Priya Singh	priya.singh@yahoo.com
4	Neha Patel	neha.patel@yahoo.com
5	Arjun Gupta	arjun.gupta@gmail.com



*/
use fs;
SELECT c.customer_id,CONCAT(c.first_name," ",c.last_name) AS full_name,c.email
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
WHERE o.total_amount >
    (
    SELECT MAX(total) AS max_beverage
    FROM (
        SELECT (
            SELECT SUM(o2.total_amount) 
            FROM Orders o2
            WHERE f.food_id = o2.food_id
            AND o2.status = "Delivered"
        ) AS total
        FROM FoodItems f
        WHERE f.category = "Beverages"
        )t1

    )

EXCEPT
SELECT c.customer_id,CONCAT(c.first_name," ",c.last_name) AS full_name,c.email
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
WHERE o.status = "Cancelled"


/* Q2
Problem Description:
The strategic analysts require a list of departments where the average employee salary is greater than the company-wide average salary, 
and which also employ at least one worker who ranks in the top earner brackets across the entire company. 
Write an SQL query using nested table derivatives,
multi-level scalar metrics, and an INTERSECT operator block to join these matching criteria groups cleanly.

case=1
output=
deptno
40

outer=
inner =
*/
use fs;
-- USING Correlated
-- SELECT deptno 
-- FROM dept d
-- WHERE (SELECT AVG(e.sal) FROM emp e WHERE e.deptno = d.deptno) > (SELECT AVG(sal) FROM emp)
-- INTERSECT
-- SELECT e.deptno 
-- FROM emp e 
-- WHERE sal = (SELECT MAX(e2.sal) FROM emp e2  );

-- USING table derivatives
SELECT deptno
FROM 
    (
    SELECT deptno,AVG(e.sal) AS average
    FROM emp e 
    GROUP BY e.deptno
    )t1
    
WHERE t1.average > (SELECT AVG(sal) FROM emp)
INTERSECT
SELECT e.deptno 
FROM emp e 
WHERE sal = (SELECT MAX(e2.sal) FROM emp e2  );


/* Q3
Problem Description:
The restaurant marketing team wants to send a promotional thank-you email to customers who have placed individual high-value orders.
Write an SQL query to retrieve the customer's full name (first name and last name combined), their email address, the order ID,
and the specific order's total amount. Use an uncorrelated subquery in the filtering clause to restrict the output to orders whose total_amount 
is strictly greater than the overall average total amount computed across all orders in the system.

case=1
output=
customer_name	email	                order_id	total_amount
Neha Patel	    neha.patel@yahoo.com	11      	600.00
Arjun Gupta	    arjun.gupta@gmail.com	14      	360.00
Amit Sharma	    amit.sharma@gmail.com	1       	300.00
Rahul Verma	    rahul.verma@gmail.com	8       	300.00
Priya Singh	    priya.singh@yahoo.com	19      	260.00
Rahul Verma	    rahul.verma@gmail.com	7       	250.00
Arjun Gupta	    arjun.gupta@gmail.com	17      	250.00
Priya Singh	    priya.singh@yahoo.com	4       	240.00

*/
use fs;
SELECT CONCAT(first_name," ",last_name) AS customer_name, email,o.order_id, o.total_amount
FROM Customers c
JOIN Orders o 
    ON c.customer_id = o.customer_id
WHERE o.total_amount >
(SELECT AVG(total_amount) FROM Orders)
ORDER BY o.total_amount DESC;


/* Q4
Problem Description:
The HR system requires a comprehensive master list showing distinct employee tracks who are either working in top salary tiers (Grade 4 or 5) 
within a department located in 'Chicago', or are direct supervisors tracking subordinates who make less than 1500 base salary. 
Use structural subqueries combined with a UNION clause to bring these distinct operational groups together.

case=1
output=
empno	ename	classification_reason
7698	BLAKE	High Salary Tier in Chicago
7902	FORD	Manages Underpaid Subordinates
7698	BLAKE	Manages Underpaid Subordinates
7788	SCOTT	Manages Underpaid Subordinates
7782	CLARK	Manages Underpaid Subordinates



*/
use fs;
SELECT  empno,ename,"High Salary Tier in Chicago" AS classification_reason
FROM emp e
JOIN salgrade s
    ON e.sal BETWEEN s.losal AND s.hisal
WHERE s.grade IN (4,5) AND EXISTS(SELECT 1 FROM dept d WHERE e.deptno =d.deptno AND d.location ="Chicago")
UNION 

SELECT  m.empno,m.ename,"Manages Underpaid Subordinates" AS classification_reason
FROM emp e
JOIN emp m
    ON e.mgr = m.empno
WHERE e.sal <1500
;


/* Q5
Problem Description:
The sales auditing coordinator wants to review bulk transaction records to monitor high-value orders.
Write an SQL query to retrieve the order ID,
the customer's first name, the food item name, the quantity ordered, and the recorded total amount from the database. Filter the records to only 
display orders where the customer purchased more than 1 quantity of that item in a single transaction, and the order's total_amount is strictly greater than 200. 
Sort the output in descending order of the total amount.

case=1
output=
order_id	first_name	food_item_name	quantity	total_amount
11	        Neha	    Chicken Biryani	    2   	600.00
14	        Arjun	    Masala Dosa	        3   	360.00
8	        Rahul	    Dal Tadka	        2   	300.00
19	        Priya	    Veg Fried Rice	    2   	260.00
4	        Priya	    Masala Dosa 	    2   	240.00




*/
use fs;
-- USING SUB QUERY
-- SELECT order_id,(SELECT first_name from Customers c WHERE c.customer_id = o.customer_id) AS first_name,(select name from FoodItems f WHERE f.food_id =o.food_id) AS food_item_name,
--     quantity,total_amount
-- FROM Orders o 
-- WHERE quantity > 1 AND total_amount > 200
-- ORDER BY total_amount DESC;

-- USING JOINS
SELECT o.order_id,
       c.first_name,
       f.name AS food_item_name,
       o.quantity,
       o.total_amount
FROM Orders o 
JOIN Customers c
    ON o.customer_id = c.customer_id
JOIN FoodItems f
    ON o.food_id = f.food_id
WHERE o.quantity > 1 AND o.total_amount > 200
ORDER BY o.total_amount DESC;




/* Q6
Problem Description:
The digital menu management team wants to highlight the single most expensive item within each distinct food category on the menu. 
Write an SQL query to pull the food item ID, name, category, and price. Implement a multi-row correlated subquery that finds items
where the price matches the maximum price computed exclusively for that matching row category.


case=1
output=
food_id	name	    category	price
2	Chicken Biryani	Main Course	300.00
3	Masala Dosa	    Breakfast	120.00
4	Samosa	        Snacks	    30.00
5	Gulab Jamun	    Desserts	50.00
6	Butter Naan     Breads  	40.00
10	Mango Lassi 	Beverages	60.00
*/
use fs;
SELECT food_id,name,category,price
FROM FoodItems f
WHERE f.price =(SELECT MAX(price) FROM FoodItems f2 WHERE f2.category = f.category)



/* Q7
Problem Description:
The operational marketing team wants to find the IDs of customers who have ordered 'Chicken Biryani' AND have ordered 'Mango Lassi', 
but have completely excluded 'Samosa' from their ordering lifetime history. Structure a combination of INTERSECT and EXCEPT clauses 
driven by internal target-matching subqueries to extract this precise segmentation.

case=1
output=
customer_id
4
*/

use fs;
-- USING JOINS
SELECT customer_id
FROM Orders o
JOIN FoodItems f 
    ON o.food_id = f.food_id
WHERE f.name = "Chicken Biryani"

INTERSECT

SELECT customer_id
FROM Orders o
JOIN FoodItems f 
    ON o.food_id = f.food_id
WHERE f.name = "Mango Lassi"

EXCEPT

SELECT customer_id
FROM Orders o
JOIN FoodItems f 
    ON o.food_id = f.food_id
WHERE f.name = "Samosa"



-- method 2  using EXISTS

-- SELECT customer_id
-- FROM Orders o
-- WHERE EXISTS(SELECT 1 FROM FoodItems f WHERE o.food_id = f.food_id AND f.name ="Chicken Biryani") 

-- INTERSECT

-- SELECT customer_id
-- FROM Orders o
-- WHERE EXISTS(SELECT 1 FROM FoodItems f WHERE o.food_id = f.food_id AND f.name = "Mango Lassi") 
 
-- EXCEPT

-- SELECT customer_id
-- FROM Orders o
-- WHERE EXISTS(SELECT 1 FROM FoodItems f WHERE o.food_id = f.food_id AND f.name ="Samosa") 


-- -- Method 3 
-- SELECT customer_id
-- FROM Orders o
-- WHERE (SELECT name FROM FoodItems f WHERE o.food_id = f.food_id) = "Chicken Biryani"

-- INTERSECT

-- SELECT customer_id
-- FROM Orders o
-- WHERE (SELECT name FROM FoodItems f WHERE o.food_id = f.food_id) = "Mango Lassi"
 
-- EXCEPT

-- SELECT customer_id
-- FROM Orders o
-- WHERE (SELECT name FROM FoodItems f WHERE o.food_id = f.food_id) = "Samosa";



  
/* Q8
Problem Description:
The payroll department wants to pinpoint specific regional departments where the cumulative operational costs (sum of all employee salaries) 
are entirely driven by staff members hired in the 1990s decade. 
Write an SQL query using nested subquery groups that evaluates 
the total salary of employees hired between 1990 and 1999 and matches it against the absolute department total payroll.

case=1
output=
deptno	dname
30	Sales
40	Operations


*/
use fs;
SELECT deptno,dname
FROM dept d
WHERE 
(SELECT SUM(e.sal)  FROM emp e WHERE YEAR(hiredate) BETWEEN "1990" AND "1999" AND e.deptno = d.deptno) 
= 
(SELECT SUM(e.sal) FROM emp e WHERE e.deptno = d.deptno);

-- Method 2 using exists and not exists
-- SELECT deptno,dname
-- FROM dept d
-- WHERE 
-- EXISTS(SELECT 1 FROM emp e WHERE e.deptno = d.deptno) AND NOT EXISTS(select 1 FROM emp e WHERE YEAR(hiredate) NOT BETWEEN "1990" AND "1999" AND e.deptno = d.deptno)


/* Q9
Problem Description:
The executive committee needs an audit report containing the details of all employees who are either 
the absolute lowest earner in their respective department, or hold the maximum tenure (earliest hire date) 
across the whole company. Bring these two distinct granular groups together into one dataset matrix 
by joining them using a UNION ALL set operator.

case=1
output=
empno	ename	deptno	audit_tag
7369	SMITH	20	Lowest Department Earner
7521	ALLEN	30	Lowest Department Earner
7654	MARTIN	40	Lowest Department Earner
7934	FORD	10	Lowest Department Earner
7839	KEVIN	40	Company Senior Tenure



*/
use fs;
SELECT empno, ename, deptno, "Lowest Department Earner" AS audit_tag
FROM emp e 
WHERE e.sal = (SELECT MIN(e2.sal) FROM emp e2 WHERE e.deptno = e2.deptno)

UNION ALL

SELECT empno, ename, deptno, "Company Senior Tenure" AS audit_tag
FROM emp e
WHERE e.hiredate = (SELECT MIN(e2.hiredate) FROM emp e2 )


/* Q10
Problem Description:
The financial data analyst wants to understand the concentration of salary distribution inside each department. 
Write an SQL query to retrieve the employee name, department number, salary, and a calculated inline column called department_contribution_percentage. 
This column must use a correlated scalar subquery to find what percentage the individual's 
salary constitutes out of the total salary pool of their own department.

case=1
output=
ename	deptno	sal	        department_contribution_percentage
CLARK	10	    2450.00	    45.79
ALLEN	10	    1600.00	    29.91
FORD	10	    1300.00	    24.30
SCOTT	20	    3000.00	    25.37
FORD	20	    3000.00	    25.37
JONES	20	    2975.00	    25.16
KEVIN	20	    1100.00	    9.30
JAMES	20	    950.00	    8.03
SMITH	20	    800.00	    6.77
BLAKE	30	    2850.00	    50.89
KEVIN	30	    1500.00	    26.79
ALLEN	30	    1250.00	    22.32
KEVIN	40	    5000.00	    80.00
MARTIN	40	    1250.00	    20.00
*/
use fs;
SELECT ename, deptno, sal,ROUND(sal/(SELECT SUM(e2.sal) AS total_salary_dept FROM emp e2 WHERE e.deptno = e2.deptno) * 100,2 )AS department_contribution_percentage
FROM emp e
ORDER BY e.deptno, e.sal DESC ;


/* IMPORTANT **** Q11 ************

Problem Description:
The business intelligence developer wants to identify high-value breakfast consumers to target with a new morning loyalty campaign.
Write a read-only SQL query to retrieve the customer's full name, email address, and their total lifetime spending across all menu categories.
Filter the output to return only those customers whose cumulative spending specifically on items in the 'Breakfast' category is 
strictly greater than the average breakfast expenditure calculated across all customers who have ordered breakfast.

case=1
output=
customer_name	email           	total_lifetime_spending
Priya Singh	priya.singh@yahoo.com	680.00
Arjun Gupta	arjun.gupta@gmail.com	920.00



*/
use fs;
SELECT CONCAT(c.first_name," ",c.last_name) AS customer_name,
        c.email, 
        SUM(o.total_amount) AS total_lifetime_spending
        
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id,first_name,last_name,email
HAVING (
            (
                SELECT SUM(o1.total_amount) 
                FROM Orders o1 
                JOIN FoodItems f 
                    ON o1.food_id = f.food_id
                WHERE o1.customer_id = c.customer_id
                    AND f.category = "Breakfast"
            )
            >
            (
             SELECT AVG(t2.total)
             FROM 
                (
                SELECT SUM(o2.total_amount) AS total
                FROM Orders o2
                JOIN FoodItems f2
                   ON o2.food_id = f2.food_id
                WHERE  f2.category = "Breakfast"
                GROUP BY o2.customer_id
                ) t2
            )
        );
        

/* Q12
Problem Description:
The HR systems division requires a comprehensive analytics list showing distinct employee tracks who meet high-profile administrative conditions. 
The report needs to display employees who are either working in top salary tiers (Grade 4 or 5) within a department located in 'Chicago', 
or are direct supervisors tracking subordinates who make less than 1500 base salary.
Use structural analytical subqueries combined with
a UNION clause to compile these distinct operational groups together.

case=1
output=
empno	ename	classification_reason
7698	BLAKE	High Salary Tier in Chicago
7902	FORD	Manages Underpaid Subordinates
7698	BLAKE	Manages Underpaid Subordinates
7788	SCOTT	Manages Underpaid Subordinates
7782	CLARK	Manages Underpaid Subordinates



*/
use fs;
SELECT empno, ename, "High Salary Tier in Chicago" AS classification_reason
FROM emp e
JOIN salgrade s 
    ON e.sal BETWEEN s.losal AND s.hisal
WHERE s.grade IN (4,5) AND EXISTS(SELECT 1 FROM dept d WHERE d.deptno = e.deptno AND d.location = "Chicago")
UNION
SELECT m.empno, m.ename,"Manages Underpaid Subordinates" AS classification_reason
FROM emp e
JOIN emp m
    ON e.mgr = m.empno
WHERE e.sal < 1500;


/* IMP **** Q13
Problem Description:
The strategic analysis team requires a list of department numbers where the average employee salary is strictly greater than the company-wide average salary.
Additionally, these departments must also employ at least one worker who ranks among the highest-paid individuals in the company (specifically,
those earning a salary greater than or equal to the second-highest salary found in the entire organization). Write an SQL query using nested table 
derivatives, multi-level metrics, and an INTERSECT operator block to join these matching criteria groups cleanly without modifying any structural data.

case=1
output=
deptno
40




*/
use fs;
SELECT deptno
FROM emp e
GROUP BY deptno
HAVING AVG(e.sal)
>(SELECT AVG(sal) FROM emp)


INTERSECT

SELECT e.deptno
FROM emp e
WHERE e.sal >= (select MAX(e2.sal) FROM emp e2 WHERE e2.sal < (SELECT MAX(e3.sal) FROM emp e3))
GROUP BY e.deptno



/* Q14
Problem Description:
The kitchen logistics team wants to identify unusually large transactional orders to optimize packaging and high-volume delivery preparation. 
Write a read-only SQL query to retrieve the order ID, customer ID, order date, food item name, and the recorded total amount for individual transactions. 
Filter the output to return only those orders where the transaction's total_amount is strictly greater than the calculated historical average total amount
spent specifically on that exact food item across the entire platform.

case=1 
output=
order_id	customer_id	order_date	        food_item_name	total_amount
11	                4	2026-06-17 11:17:55	Chicken Biryani	600.00
14	                5	2026-06-17 11:17:55	Masala Dosa	360.00
19	                2	2026-06-17 11:17:55	Veg Fried Rice	260.00
12	                4	2026-06-17 11:17:55	Gulab Jamun	200.00
18	                1	2026-06-17 11:17:55	Chole Bhature	200.00
20	                3	2026-06-17 11:17:55	Mango Lassi	180.00
16	                5	2026-06-17 11:17:55	Butter Naan	160.00
15	                5	2026-06-17 11:17:55	Samosa	150.00

*/
use fs;
SELECT o.order_id,o.customer_id,o.order_date,f.name AS food_item_name, o.total_amount AS total_amount
FROM Orders o 
JOIN FoodItems f
    ON o.food_id = f.food_id
WHERE o.total_amount >
    (
    SELECT AVG(o2.total_amount) 
    FROM Orders o2 
    WHERE o2.food_id = o.food_id
    )
ORDER BY o.total_amount DESC;




/* IMP  Q15
Problem Description:
The restaurant operations division wants to find out which food items are the primary revenue drivers within each menu section. 
Write a read-only SQL query that constructs a derived table to compute the total revenue generated by each food item 
(filtered only for orders that have been successfully 'Delivered'). 
Combine this with a correlated subquery to filter and return the food item name, category, and total revenue for the food items 
that have achieved the absolute highest revenue within their respective menu category.

case=1
output=
food_item_name	category	total_revenue
Masala Dosa	    Breakfast	360.00
Chicken Biryani	Main Course	300.00
Dal Tadka   	Main Course	300.00
Samosa  	    Snacks	    270.00
Butter Naan     Breads  	240.00
Mango Lassi	    Beverages	180.00
Gulab Jamun	    Desserts	150.00



*/
use fs;
SELECT name AS food_item_name,category,SUM(total_amount) AS total_revenue
FROM Orders o 
JOIN FoodItems f
    ON f.food_id = o.food_id
WHERE o.status ="Delivered"
GROUP BY name,category 
HAVING SUM(total_amount) =
    ( 
    SELECT MAX(total) 
    FROM (
            SELECT name,category,SUM(total_amount) AS total
            FROM Orders o1
            JOIN FoodItems f1
                ON f1.food_id = o1.food_id
            WHERE o1.status = "Delivered"
                AND f1.category = f.category 
            GROUP BY name,category 
            
        )t1
    )
ORDER BY total_revenue DESC;



/* DAY 17 Q1
Problem Description:
The restaurant sales audit team wants to flag orders that have recorded an exceptionally high quantity of items 
relative to typical customer selections.Write a read-only SQL query to retrieve the order ID, customer ID, food ID, and quantity.
Filter the results using an uncorrelated subquery in the WHERE clause to display only those orders where the quantity ordered is strictly greater 
than the overall average quantity calculated across all orders in the database.

case=1
output=
order_id	customer_id	food_id	quantity
15	            5          	4   	5
6	            2          	4   	4
12	            4          	5   	4
16	            5          	6   	4
2	            1          	5   	3
14	            5          	3   	3
20	            3          	10  	3



*/
use fs;
SELECT o.order_id, o.customer_id,o.food_id,o.quantity
FROM Orders o 
WHERE o.quantity > (SELECT AVG(o.quantity) FROM Orders o)
ORDER BY o.quantity DESC;




/* Q2
Problem Description:
The operations desk wants to identify active premium menu categories that have successfully processed transactions. 
Write an SQL query that lists all unique food categories from the FoodItems table where the individual item price is greater than 150.
Use an INTERSECT operator to match these against categories that have at least one recorded entry in the Orders table.

case=1
output=
category
Main Course



*/
USE fs;
SELECT DISTINCT category
FROM FoodItems
where price > 150
INTERSECT 
SELECT category
FROM FoodItems f
WHERE EXISTS(
        SELECT 1 FROM
        Orders o
        WHERE f.food_id = o.food_id)



/* Q3
Problem Description:
The regional managers require a clean breakdown of the employee payroll to analyze individual salary weights against company baselines. 
Write a read-only SQL query to list each employee's name, their department number, and their exact salary from the emp table. 
Include a dynamically calculated column named company_max_salary using a scalar subquery to display the absolute highest salary alongside every employee row.

case=1
output=
employee_name	deptno	salary	company_max_salary
KEVIN	        40	    5000.00	    5000.00
SCOTT	        20	    3000.00	    5000.00
FORD	        20	    3000.00	    5000.00
JONES	        20	    2975.00	    5000.00
BLAKE	        30	    2850.00	    5000.00
CLARK	        10	    2450.00	    5000.00
ALLEN	        10	    1600.00	    5000.00
KEVIN	        30	    1500.00	    5000.00
FORD	        10	    1300.00	    5000.00
ALLEN	        30	    1250.00	    5000.00
MARTIN	        40	    1250.00	    5000.00
KEVIN	        20	    1100.00	    5000.00
JAMES	        20	    950.00	    5000.00
SMITH	        20	    800.00	    5000.00

*/
USE fs;
SELECT ename AS employee_name, deptno, sal AS salary, (SELECT MAX(sal) FROM emp) AS company_max_salary
FROM emp 
ORDER BY salary DESC



/* Q4
Problem Description:
The HR department wants to audit departments that have a functional management footprint. 
Write a read-only SQL query to retrieve the department number and department name from the dept table.
Filter the output using an EXISTS correlated subquery to return only those departments that currently 
act as a workspace for at least one employee holding the job title of 'MANAGER'.

case=1
output=
deptno	dname
10	Accounting
20	Research
30	Sales


*/
use fs;
SELECT deptno,dname
FROM dept d
WHERE EXISTS(SELECT 1 FROM emp e WHERE d.deptno = e.deptno AND e.job = "MANAGER");



/* Q5
An enterprise data analyst needs to audit high-performing customer accounts to identify regional market leaders.
Write a read-only SQL query to find the customer ID, their full name (first name and last name combined), their city address, 
and their total lifetime expenditure across all orders.

Filter the results using a complex correlated subquery inside the HAVING clause so that you only return customers whose 
cumulative lifetime spending is strictly greater than the historical average of individual transaction amounts placed by all customers living in that exact same city.

case=1
output=
customer_id	customer_name	city_address	    total_customer_lifetime_spend
4	        Neha Patel	    Ahmedabad, India	1020.00
5	        Arjun Gupta	    Hyderabad, India	920.00
3	        Rahul Verma	    Bengaluru, India	860.00
1	        Amit Sharma	    Delhi, India	    730.00
2	        Priya Singh	    Mumbai, India	    680.00

*/
use fs;
SELECT c.customer_id, CONCAT(first_name," ",last_name) AS customer_name, c.address AS city_address,SUM(o.total_amount) AS total_customer_lifetime_spend
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY customer_id,first_name,last_name, address
HAVING SUM(o.total_amount) >    
    (
    SELECT AVG(o2.total_amount) 
    FROM Orders o2 
    JOIN Customers c2 ON c2.customer_id = o2.customer_id 
    WHERE c.address = c2.address
    )
ORDER BY total_customer_lifetime_spend DESC;




/* Q6
Problem Description:
The analytics desk wants to compile a list of highly engaged customer contacts for a targeted outreach program. 
Write a read-only query that uses the UNION operator to find the unique customer IDs, first names, and emails of customers
who have either placed a single order exceeding a quantity of 3 or have successfully spent more than 300.00 in a single transaction.

case=1
output=
customer_id	first_name	email
2	Priya	priya.singh@yahoo.com
4	Neha	neha.patel@yahoo.com
5	Arjun	arjun.gupta@gmail.com
*/
use fs;
SELECT customer_id, first_name,email
FROM Customers c
WHERE EXISTS(SELECT 1 FROM Orders o WHERE c.customer_id = o.customer_id AND o.quantity >3 )

UNION 

SELECT customer_id, first_name,email
FROM Customers c
WHERE EXISTS(SELECT 1 FROM Orders o WHERE c.customer_id = o.customer_id AND o.total_amount > 300)


/* IMP Q7
Problem Description:
An enterprise HR metrics developer needs to flag anomalous salaries where individuals out-earn the localized aggregate averages. 
Write a read-only SQL query to extract the employee name, department name, location, and salary from the emp and dept tables. 
The query must use nested subqueries to filter and return only those employees whose salary is strictly greater than the average 
salary of the entire department that holds the maximum aggregate payroll budget across the company.  

case=1
output=
employee_name   department_name	location	salary
JONES	        Research	    Dallas	    2975.00
BLAKE	        Sales	        Chicago	    2850.00
CLARK	        Accounting	    New York    2450.00
SCOTT	        Research	    Dallas	    3000.00
KEVIN	        Operations	    Boston	    5000.00
FORD	        Research	    Dallas	    3000.00

*/
use fs;

SELECT e.ename AS employee_name,d.dname AS department_name ,d.location, e.sal AS salary
FROM emp e
JOIN dept d
ON e.deptno = d.deptno
WHERE e.sal > (
SELECT AVG(sal)
FROM emp e
WHERE e.deptno =
    (
        SELECT deptno AS avg_dept
        FROM emp e
        GROUP BY deptno
        HAVING SUM(sal)=
                (
                    SELECT MAX(total)
                    FROM (
                        SELECT  deptno,SUM(e1.sal) AS total
                        FROM emp e1 
                        GROUP BY e1.deptno
                    )t1
                )

    )
    );




/* Q8
Problem Description:
The financial compensation auditor needs to verify leadership pay distributions inside organizational units.
Write a read-only SQL query to select the employee number, employee name, department number, salary, and corresponding salary grade 
tier from the emp and salgrade tables. The logic must use a correlated subquery to filter and return only those individuals
whose personal grade is strictly higher than the average salary grade tier computed across their specific department node

case=1
output=
empno	ename	deptno	sal	grade
7782	CLARK	10	2450.00	4
7499	ALLEN	10	1600.00	3
7782	CLARK	10	2450.00	3
7566	JONES	20	2975.00	4
7788	SCOTT	20	3000.00	4
7902	FORD	20	3000.00	4
7566	JONES	20	2975.00	3
7788	SCOTT	20	3000.00	3
7902	FORD	20	3000.00	3
7698	BLAKE	30	2850.00	4
7698	BLAKE	30	2850.00	3
7844	KEVIN	30	1500.00	3
7839	KEVIN	40	5000.00	6
7839	KEVIN	40	5000.00	5
7839	KEVIN	40	5000.00	4



*/
use fs;
SELECT empno, ename,deptno,sal,s.grade
FROM emp e
JOIN salgrade s ON e.sal BETWEEN s.losal AND s.hisal
WHERE s.grade > 
    (
        SELECT AVG(grade) FROM salgrade s1 JOIN emp e2 ON e2.sal BETWEEN s1.losal AND s1.hisal WHERE e.deptno = e2.deptno  
    )
ORDER BY deptno,s.grade DESC;


/* IMP Q9
The internal audit department needs a unified exception report detailing extreme pay scenarios across corporate levels. 
Write a read-only SQL query that extracts the employee name, their supervisor's name, and their salary for employees 
who earn more money than their direct supervisor. Use a UNION ALL block to append another dataset matching high-earner outliers: 
employees whose base salary is strictly greater than the calculated average salary of all active managers combined.

case=1
output=
employee_name	manager_name	employee_salary
SCOTT	        JONES         	3000.00
FORD	        JONES       	3000.00
KEVIN	N/A - System Outlier	5000.00

*/
use fs;
SELECT e.ename AS employee_name, m.ename AS manager_name,e.sal AS employee_salary
FROM emp e
JOIN emp m ON e.mgr = m.empno
WHERE e.sal >  m.sal

UNION ALL

SELECT e.ename AS employee_name, "N/A - System Outlier" AS manager_name,e.sal AS employee_salary
FROM emp e
WHERE e.sal >  
    (
    SELECT AVG(manager_sal) 
    FROM (
            SELECT DISTINCT m.empno, m.sal AS manager_sal 
            FROM emp m 
            JOIN emp e1 
            ON e1.mgr = m.empno 
         )t1
    );


/* Q10
Problem Description:
The kitchen inventory control office wants to identify menu choices that haven't registered any successful order fulfillments to optimize stocking space. 
Write a read-only SQL query to find the food ID, item name, category, and price of items inside the FoodItems table whose food_id is entirely absent from
transactional records currently flagged with a status of 'Delivered'.  

case=1
output=

food_id	name	                category	price
1	    Paneer Butter Masala	Main Course	250.00
*/
use fs;
SELECT food_id, name, category, price 
FROM FoodItems f
WHERE NOT EXISTS(SELECT 1 FROM Orders o WHERE o.food_id = f.food_id AND o.status = 'Delivered');



/* Q11
Problem Description:
The operations team wants a diagnostic view of current processing streams that contrasts active transactions right alongside user historic order volumes.
Write a read-only SQL query to output the order ID, customer ID, order date, status, and total amount. Join the main table against an inline derived subquery 
table that pre-calculates the absolute count of historical orders placed by each unique customer ID.

case=1
output=
order_id	customer_id	order_date	status	total_amount	total_customer_orders
1	1	2026-06-17 11:17:55	Delivered	300.00	4
2	1	2026-06-17 11:17:55	Delivered	150.00	4
3	1	2026-06-17 11:17:55	Delivered	80.00	4
4	2	2026-06-17 11:17:55	Preparing	240.00	4
5	2	2026-06-17 11:17:55	Preparing	60.00	4
6	2	2026-06-17 11:17:55	Delivered	120.00	4
7	3	2026-06-17 11:17:55	Cancelled	250.00	4
8	3	2026-06-17 11:17:55	Delivered	300.00	4
9	3	2026-06-17 11:17:55	Delivered	130.00	4
10	4	2026-06-17 11:17:55	Pending	100.00	4
11	4	2026-06-17 11:17:55	Pending	600.00	4
12	4	2026-06-17 11:17:55	Preparing	200.00	4
13	4	2026-06-17 11:17:55	Preparing	120.00	4
14	5	2026-06-17 11:17:55	Delivered	360.00	4
15	5	2026-06-17 11:17:55	Delivered	150.00	4
16	5	2026-06-17 11:17:55	Delivered	160.00	4
17	5	2026-06-17 11:17:55	Preparing	250.00	4
18	1	2026-06-17 11:17:55	Delivered	200.00	4
19	2	2026-06-17 11:17:55	Pending	260.00	4
20	3	2026-06-17 11:17:55	Delivered	180.00	4



*/
use fs;
SELECT o.order_id,o.customer_id,o.order_date,o.status,o.total_amount, total_customer_orders
FROM Orders o
JOIN 
    (
    SELECT o1.customer_id,COUNT(o1.customer_id) AS total_customer_orders 
    FROM Orders o1
    GROUP BY o1.customer_id
    )t1
ON o.customer_id = t1.customer_id;


/* Q12
A fraud detection analyst wants to discover highly localized transaction spikes where a consumer places an order that deviates significantly 
from their personal buying choices. Write a read-only SQL query to retrieve the order ID, customer ID, food ID, and total amount from the Orders table.
The query must filter records using an optimized correlated subquery to return only those orders whose individual total_amount is strictly
greater than twice the historical average order amount calculated for that specific customer's profile.

case=1
output=
order_id	customer_id	food_id	total_amount
11	        4	        2      	600.00



*/
use fs;
SELECT order_id, customer_id, food_id, total_amount 
FROM Orders o
WHERE total_amount > 
    (
    SELECT AVG(o2.total_amount ) * 2
    FROM Orders o2 
    WHERE o.customer_id = o2.customer_id
    );



/* Q13
Problem Description:
The marketing division wants to identify dominant menu items that hold a high market share within their menu sections to create focused combos. 
Write a read-only SQL query to calculate the food item name, category, and total revenue pool for successfully processed rows. Use an advanced 
correlated subquery inside the HAVING clause to filter the final dataset to show only those individual food items whose cumulative sales account 
for more than 35% of the entire revenue generated within that product's parent menu category.

case=1
output=
food_item_name	    category	    item_total_revenue
Chicken Biryani 	Main Course	    900.00
Masala Dosa 	    Breakfast   	600.00
Mango Lassi	        Beverages   	360.00
Gulab Jamun	        Desserts    	350.00
Samosa	            Snacks  	    270.00
Butter Naan 	    Breads  	    240.00
*/
use fs;
SELECT f.name AS food_item_name, f.category, SUM(o.total_amount) AS item_total_revenue
FROM FoodItems f 
JOIN Orders o ON f.food_id = o.food_id

GROUP BY f.name,f.category
HAVING SUM(o.total_amount) > 
    (SELECT SUM(o2.total_amount) * 0.35
    FROM Orders o2
    JOIN FoodItems f2 ON o2.food_id = f2.food_id
    WHERE f.category =f2.category 
    )
ORDER BY item_total_revenue DESC;




/* Q14
Problem Description:
The HR planning board requires a workspace distribution matrix to analyze operational units. Write a read-only SQL query to find the department number, 
department name, and the sum of salaries from the employee database. Filter the final rows using a multi-layered nested subquery 
inside the HAVING clause so that you only return organizational units whose total active employee headcount is strictly greater than 
the average employee headcount computed across all active departments in the enterprise.

case=1
output=
deptno	dname   	total_department_payroll
20	    Research	11825.00



*/
/*

GROUP by
HAVING count(empno)> avg() from SUM() group by

*/

use fs;
SELECT d.deptno,d.dname,SUM(e.sal) AS total_department_payroll
FROM dept d
JOIN emp e ON d.deptno = e.deptno
GROUP BY d.deptno,d.dname
HAVING COUNT(e.empno)>
    (SELECT AVG(total)
    FROM 
        (SELECT COUNT(e2.empno) AS total
        FROM emp e2
        GROUP BY e2.deptno
        
    )t1
    );


/* IMP Q15
Problem Description:
The senior menu performance analyst wants to find high-velocity food items that consistently drive strong transactional volume within their food groups.
Write a read-only SQL query to retrieve the food item name, category, and total quantities sold across all successfully processed transactions.

Filter the output using a correlated subquery inside the HAVING clause to return only those individual food items whose cumulative quantity sold
is strictly greater than the average individual quantity ordered for any single transaction within that exact same food category.



case=1
output=
food_item_name	category	total_quantity_sold
Samosa	        Snacks	    9
Butter Naan 	Breads  	6
Masala Dosa 	Breakfast	3
Dal Tadka   	Main Course	2



*/
/*
SUM(qt)
group by name,cat
having sum(qt)> AVg() from fdit where f1.cat = f2.cat
*/
use fs;
SELECT name AS food_item_name, category , SUM(o.quantity) AS total_quantity_sold
FROM FoodItems f
JOIN Orders o  ON f.food_id = o.food_id
WHERE o.status = "Delivered"
GROUP BY f.food_id,name,category
HAVING SUM(o.quantity) >
    (
    SELECT AVG(o2.quantity) 
    FROM Orders o2 
    JOIN FoodItems f2 ON o2.food_id = f2.food_id 
    WHERE f.category = f2.category AND o2.status = "Delivered"
    )
ORDER BY total_quantity_sold DESC;

